### ISSUE TITLE
Journal abbreviations

### ISSUE THREAD

**Issue by schneiderfelipe** [devmessias/journalabbrev#18]
Hi,

It is sometimes necessary in my field to abbreviate journal titles. For instance,

**THE JOURNAL OF PHYSICAL CHEMISTRY C**

becomes

**J PHYS CHEM C**

Is it at the moment possible with bibcure? Would that be an useful feature? I could help with a PR.

A list of abbreviations can be [found in the web](http://images.webofknowledge.com/images/help/WOS/0-9_abrvjt.html).

**Comment by homocomputeris** [comment]
Yes, it will ask you:
```
bibcure -i ill.bib -o cured.bib
Update bibs using DOI field?y(yes)/n(do nothing)y
Get DOI absent using the title?y(yes, automatic)/m(manual)/n(do nothing)y
Check if arxiv have been published?y(yes, automatic)/m(manual)/n(do nothing)y
71 bibs >> are not journal
61 bibs >> are out db
130 bibs >> can be abbreviated
The next items does not exist in database.
Manually update your database?y(yes)/n(do nothing)n
Abbreviate everthing?y(yes, automatic)/m(manual)/n(do nothing)n
```
The problem is that it sometimes gives complete rubbish, e.g. [this DOI](https://doi.org/10.1016%2Fj.commatsci.2004.11.002) is abbreviated as `Nato. Sc. S. Ss. Iii. C. S.`.

You can try Mendeley: import your bib file, Tools - Options - BibTeX - Use journal abbreviation; then export your file.
Or try [Automatic Journal Title Abbreviation Package](http://www.compholio.com/latex/jabbrv/).

**Comment by homocomputeris** [comment]
Abbreviation also works in JabRef and there you can create custom rules.

**Comment by schneiderfelipe** [comment]
Thanks! In principle, bibcure does everything I need in terms of abbreviations.
